### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by kellyabreu** [samgoree/KohonenCategorizer#1]
Please,

Could you put an example of dataset for KohonenWordCategorizer?

Tks!

**Comment by samgoree** [comment]
Hi kellyabreau,

I no longer have access to the data that was used for this project (it was a few years ago and I am no longer in contact with the research team I was working with). I also wouldn't advise using this code as a starting point for any other investigations into SOMs, we had a poor approach.

If you have any questions about unsupervised neural network-inspired techniques, I'd be happy to help!
